### PR TITLE
README: install gnupg-curl before fetching key

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by xeffyr** [comment]
Usually, installing dirmngr should be enough. But if someone prefers GnuPG v1.x.x, gnupg-curl may be needed.

**Comment by Grimler91** [comment]
Ah, I subscribed on my tablet and got an error. But I guess that was due to gnupg being installed and used instead of gnupg2. We really should remove gnupg2 from the main repo..

**Comment by xeffyr** [comment]
> We really should remove gnupg2 from the main repo..

gnupg v1.4.x maybe ?

**Comment by Grimler91** [comment]
Err, yes, I meant gnupg of course.

**Pull request merged**
